name: CI

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        version: [stable, unstable, development-target]
    container:
      image: ghcr.io/elementary/docker:${{ matrix.version }}

    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: |
          apt update
          apt install -y libhandy-1-dev libcanberra-dev libcanberra-gtk3-dev libgranite-dev libgtk-3-dev meson valac
      - name: Build
        env:
          DESTDIR: out
        run: |
          meson build
          ninja -C build
          ninja -C build install

  lint:
    runs-on: ubuntu-latest

    container:
      image: valalang/lint

    steps:
      - uses: actions/checkout@v3
      - name: Lint
        run: io.elementary.vala-lint -d .
